ARG PYTHON_VERSION={{ cookiecutter.__python_short_version }}
FROM ghcr.io/multi-py/python-celery:py${PYTHON_VERSION}-slim-LATEST

ENV APP_MODULE={{ cookiecutter.__package_slug }}.celery:celery

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

{%- if cookiecutter.include_sqlalchemy == "y" %}
RUN apt-get update && apt-get install -y netcat && rm -rf /var/lib/apt/lists/*
{%- endif %}

COPY ./docker/celery/prestart.sh /app/prestart.sh
COPY ./ /app
